#!/usr/bin/php -q
<?php
include ("nessusfunctions.php");

#Testing

$shortopts = "";

$longopts = array(
  "host:",
  "user:",
  "pass:",
  "list::",
  "scan::",
  "id::",
  "name::",
);
  
$options = getopt($shortopts, $longopts);

if (!isset($options["host"]) || !isset($options["user"]) || !isset($options["pass"])) {
  print("Must set hostname: --host https://somehost:8843 \n");
  print("Must set user: --user someuser \n");
  print("Must set password: --pass somepass \n");
  return 0;
}
else {
  $nessus_host = $options["host"];
  $user = $options["user"];
  $pass = $options["pass"];

  $token = get_logintoken($nessus_host, $user, $pass);
  //print('Token is: ' . $token . "\n");
}

if (isset($options["scan"])) {
  if($options["scan"] == "start") {
    print("Start...\n");
  }
  else if((($options["scan"] == "stop") || ($options["scan"] == "pause") || ($options["scan"] == "resume")) && isset($options["id"])) {
    if ($options["id"]) {
      if($options["scan"] == "stop") {
        print("Stop...\n");
      }
      else if($options["scan"] == "pause") {
        print("Pause...\n");
      }
      else if($options["scan"] == "resume") {
        print("Resume...\n");
      }
    }
    else {
    print("Usage: --scan={stop|pause|resume} --id=<scan_id>\n");
    }
  }
  else {
    print("Usage: --scan=start\n");
    print("Or: --scan={stop|pause|resume} --id=<scan_id>\n");
  }
}

if (isset($options["list"])) {
  if($options["list"] == "scan") {
    print("Listing scans...\n");
    list_scan_jobs($nessus_host, $token);
  }
  else if($options["list"] == "report") {
    print("Listing reports...\n");
  }
  else if($options["list"] == "policy") {
    print("Listing policies...\n");
    policy_list($nessus_host, $token);
  }
  else {
    print("Usage: --scan={scan|report|policy}\n");
  }
}

